version: "3.9"
services:
  rabbit-mq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
# docker compose up -> to run the file
# docker compose up --build -> to build
# docker compose watch -> to watch for changes
